<?php
  
  /**
   * Implements hook_help().
   *
   * Displays help and module information.
   */
  function github_commits_help($path, $arg) {
    switch ($path) {
      case "admin/help#github_commits":
      return '<p>' . t("Displays current Git-commits from a GitHub-repository.") . '</p>';
      break;
    }
  }

  /**
   * Implements hook_block_info().
   * 
   * Defines the module as a block module.
   */
  function github_commits_block_info() {
    $blocks['github_commits'] = array(
      'info' => t('GitHub Commits'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
  }

  /**
   * Implements hook_block_view().
   */
  function github_commits_block_view($delta = '') {
    switch($delta){
      case 'github_commits':
        $block['subject'] = t('GitHub Commits');
        if(user_access('access content')){

          //Array to contain items for the block to render.
          $items = array();
          
          //Iterate over the resultset and format as links.
          for ($i = 0; $i < 5; $i ++) {
            $items[] = array(
              'data' => l('This is '.($i+1), '#'),
            );
          }
        
          if (empty($items)) { //No content in the last week.
            $block['content'] = t('No posts available.');  
          } 
          else {
            //Pass data through theme function.
            $block['content'] = theme('item_list', array(
              'items' => $items));
          }
        }
      return $block;
    }
    
  }